### ISSUE TITLE
TinyMCE Configurations

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/colligo#30]

**Comment by blalbrit** [comment]
Acceptance Criteria:

1) As a curator creating annotations, I want to be able to choose which alphabet I'm working with (among Latin, Greek, and Hebrew). When I choose that alphabet, I want my annotations to be encoded properly so that when they appear in a display they will render correctly. https://github.com/ProjectMirador/mirador/issues/1252

2) As a curator creating annotations, I want to be able to choose the directionality of my writing: left-to-right, right-to-left, or bi-directional. https://github.com/ProjectMirador/mirador/issues/1251

3) As a curator creating annotations, I want to be able to configure the size of my text entry box to be larger if I am entering a long annotation. https://github.com/ProjectMirador/mirador/issues/1261

4) As a curator creating annotations, I want to be able to create footnotes within my annotation. No ticket yet - if easily configurable in TinyMCE add it, otherwise lower-priority for the moment.

5) As a curator, when creating annotations, if possible I would prefer that the text entry box not overlay the region of interest I'm annotating. https://github.com/ProjectMirador/mirador/issues/1260 . Since both boxes can be dragged currently to avoid the overlay, this is a nice-to-have if easily implemented.

**Comment by blalbrit** [comment]
6. As a curator, I want to be able to select tags from a controlled vocabulary drop-down. Additionally, if there can be a distinction between required tags (creator, for example) and optional tags that would be desirable. https://github.com/ProjectMirador/mirador/issues/1259

**Comment by jkeck** [comment]
Just as an update on this, 1 is finished, 2 is in progress, 3 & 5 will be solved by integrating search within and annotations and are not really actionable on their own.
