### ISSUE TITLE
UI improvements for Mirador annotation displays

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/colligo#31]
This is a story/proxy ticket to cover several tickets in the Mirador code-base. See details below.

**Comment by blalbrit** [comment]
Acceptance criteria (note, some of these may be de-prioritized based on the annotation sidebar work below):

1) As a curator or viewer, if I have added an audio/video/image annotation, I want the viewing box (on roll-over) not to cut off any part of the annotation body. https://github.com/ProjectMirador/mirador/issues/1263

2) As a curator or viewer, I expect the annotation body *not* to overlay the region of interest being annotated when viewing the annotation.  Related to https://github.com/ProjectMirador/mirador/issues/1260 put for annotation display instead of creation.

3) Implement side-panel annotation view and SearchWithin. More details and spec at https://github.com/ProjectMirador/mirador/issues/1256.

**Comment by jkeck** [comment]
Closing this proxy ticket now that we have Mirador in our Waffle board.

ProjectMirador/mirador#1256,  ProjectMirador/mirador#1260, and  ProjectMirador/mirador#1263 are now all in the `On deck` column in the place of this ticket.
