### ISSUE TITLE
Stanford-specific Mirador Deploy Pattern

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/colligo#37]
@efahy has thought somewhat about this - needs more details.

**Comment by mejackreed** [comment]
I wonder too if this will change when we do more with Mirador@SUL. For example: what if we need an app to serve mirador to provide a proxy?

**Comment by drh-stanford** [comment]
are we fully blocked on this pending decision? 

can we select a deployment tool in the meantime? Capistrano does have support for both npm and rails -- https://github.com/capistrano/npm/

**Comment by blalbrit** [comment]
@drh-stanford 👍  - @eefahy has thought about Mirador deployment options and should be able to weigh in.

**Comment by mejackreed** [comment]
Could this ticket be moved to https://github.com/sul-dlss/mirador_sul ?

**Comment by blalbrit** [comment]
yes, and should - my bad for getting it in the wrong repo.
