### ISSUE TITLE
Get stanford servers created for colligo

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/colligo#38]
- [x] request and have created dev, stage, prod

Rails apps, connection to sul-solr, local db should be fine

**Comment by mejackreed** [comment]
@blalbrit can you comment on the SLA for these?

**Comment by blalbrit** [comment]
We currently have sul-dms-discovery-{stage,prod} . Do we also need a -dev @mejackreed or are the two enough?

**Comment by mejackreed** [comment]
2 is probably fine. Anything on sul-dms-discovery boxes that we need to be aware of?

**Comment by blalbrit** [comment]
nope - as far as I know they have never been used. We can check with @eefahy to make sure they're config'd as expected. user is dms.
