### ISSUE TITLE
repository images for home page

### ISSUE THREAD

**Issue by jvine** [sul-dlss/colligo#4]
![parker-colligo](https://cloud.githubusercontent.com/assets/6945691/11727363/429761b0-9f38-11e5-9adc-f570a30d61e9.png)

![sul-colligo](https://cloud.githubusercontent.com/assets/6945691/11727362/42900712-9f38-11e5-8c01-663904ea9f3f.png)

![walters-colligo](https://cloud.githubusercontent.com/assets/6945691/11727364/42986c04-9f38-11e5-863b-8c55eee93169.png)

**Comment by anusharanganathan** [comment]
Thanks. Have downloaded these images.
