### ISSUE TITLE
Connect deployed app to solr

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/colligo#43]
Question for @blalbrit is there a current sul-solr core that we should be connecting stage, prod to?

How do we index data? What data do we index?

**Comment by blalbrit** [comment]
@eefahy - do we have a core that the team can use on stage at the moment? If not, would you be able to file tix for both stage and prod cores?

@mejackreed - indexing is currently handled by rake tasks in the code. We should discuss whether this is adequate or if there is an in-app solution that could be considered in scope (given a list of IIIF manifests, can those be indexed/re-indexed within the app - like Spotlight does). The data to index will be different for Stanford and Vatican deploys. For now, let's use the fixture data in the current codebase. In any case, what is being indexed are IIIF manifests from multiple sources. Vatican will be homogeneous so a mapping only will happen once. Stanford will be an ongoing, expanding set requiring new mappings - something that is on my plate to keep up with.

**Comment by jkeck** [comment]
Investigating indexing strategy ticketed in #44
