### ISSUE TITLE
Enable annotation-creation & storage functionality in embedded Mirador

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/colligo#64]
Currently, the embedded Mirador in Colligo is "read only". We would like to turn on all annotation functionality in the latest version of Mirador so that a curator can use the full suite of tools including all of the image manipulation tools to investigate and annotate materials.

**Comment by mejackreed** [comment]
In discussion with the team during planning, we want to get the Vatican team unblocked on annotation creation. The quickest way for us to do that is an update to their colligo instance and a small update to their static mirador configurations.

From there maybe this could be turned on, but i think we need a better understanding about the Vatican's indexing process for colligo.

**Comment by mejackreed** [comment]
Resolved in #69
