### ISSUE TITLE
Import annotations from external source into app

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/colligo#66]
At the moment, the Vatican team has roughly 600 annotations in Simple Annotation Store / SOLR. These need to be:

- [x] exported from the current stack
- [x] imported into Colligo
- [x] additional machine-generated annotations also need to be imported (so please provide a method & target for annotation import - whether individual annos, anno lists, etc. is up to the implementation team)

**Comment by mejackreed** [comment]
Here is a task designed to import the annotations: https://github.com/mejackreed/annotot/compare/import-anno-lists?expand=1

One issue that I am seeing is that the annotations (from SAS) are being stored correctly, but not displayed in Annotot/Colligo

**Comment by mejackreed** [comment]
This was resolved upstream in Annotot with an import + remediation task.
