### ISSUE TITLE
Export annotations as annotation lists / json

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/colligo#67]
As a user, I want to be able to export all of my annotations from Colligo as annotation lists in json documents [models available if needed]

**Comment by mejackreed** [comment]
Where do you want these exported to? Is an API endpoint good enough? Or do you also want them saved to a local disk?

**Comment by mejackreed** [comment]
version 0.2.1 of annotot provides a json endpoint (by canvas uri) as an AnnotationList. Is this acceptable?

**Comment by mejackreed** [comment]
Resolved in #69 by providing an API endpoint.
